name: Push

on: [ push ]

jobs:
    Linux:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   uses: actions/setup-python@v5
                with:
                    python-version: 3.12

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip flake8
                    python -m pip install -r requirements.txt


            -   name: Code linting
                run: flake8 . --count --select=E9,F63,F7,F82 --show-source --exit-zero --max-complexity=10 --max-line-length=140  --statistics
